version: '3.8'
 
services:
    mono-api:
      image: joseluis008/711-mono-api:latest
      container_name: mono-api
      environment:
        PORT: ${PORT}
        MONGO_URL: ${MONGO_URL_DOCKER}
        MONGO_DB: ${MONGO_DB}
      ports:
        - "3000:3000"
      depends_on:
        - mongo

    # mono-api:
    #       build: .
    #       container_name: mono-api
    #       ports:
    #         - "3000:3000"
    #       depends_on:
    #         - mongo

    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - "27017:27017"
        volumes:
            - mongo_db:/data/db
 
volumes:
    mongo_db:
    